package templates

const (
	Swift = `
//
// generated by otfdocgen, a go-lang OTF icon font generator
//

import UIKit
    
/**
 Different Glyphs for runes in {{print .Name}} 

 [OTFDocGen](https://github.com/kevinscardina/swift-otficon)
 */
enum {{print .TypeName}}: String, CustomStringConvertible, CaseIterable {
	/// The {{print .Name}} as a UIFont
	static func font(size:CGFloat) -> UIFont? {
		return UIFont(name: "{{print .Name}}", size: size)
	}

	{{range .Glyphs}} case {{print .Name}} = "\u{{"{"}}{{print .HexString}}{{"}"}}"
	{{end}}

	/// Gets a String of the icon
	var string: String? {
		return self.rawValue
	}
    
	/// Convenience
	var description: String {
		return string ?? "?"
	}
}
`
)
